name: "hatilvgl"
version: "0.1"

files:
  - tiles_lvgl.cpp
  - ha_ws_client.cpp
  - hatilvgl.cpp
  - hatilvgl.h
  - tile_widget_clock.cpp
  - tile_widget_energy.cpp
  - tile_widget_media.cpp
  - tile_widget_navigate.cpp
  - tile_widget_scene.cpp
  - tile_widget_sensor.cpp
  - tile_widget_switch.cpp
  - tile_widget_text.cpp
  - tile_widget_weather.cpp
  - tile_widget_climate.cpp
  - tile_widget_camera.cpp
  - tile_widget_settings.cpp
  - tiles_lvgl.h
  - ha_ws_client.h
  - hatilvgl.h

includes:
  - tiles_lvgl.h
  - ha_ws_client.h

dependencies:
  - lvgl
  - spiffs

idf_components:
  - espressif/esp_websocket_client@1.8.0
