packages:
    - !include { file: switch.yaml, vars: { id: buro, entity: switch.st_buro } }
    - !include { file: switch.yaml, vars: { id: buerom, entity: switch.st_buerom } }
    - !include { file: switch.yaml, vars: { id: keller, entity: switch.st_keller } } 

sensor:
  - platform: homeassistant
    id: sensor_7inch_bme280_temperature
    entity_id: sensor.7inch_bme280_temperature
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_7inch_bme280_temperature
            text:
              format: "%.1f"
              args: [ x ]
  - platform: homeassistant
    id: sensor_7inch_bme280_humidity
    entity_id: sensor.7inch_bme280_humidity
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_7inch_bme280_humidity
            text:
              format: "%.1f"
              args: [ x ]
  - platform: homeassistant
    id: sensor_7inch_bme280_pressure
    entity_id: sensor.7inch_bme280_pressure
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_7inch_bme280_pressure
            text:
              format: "%.1f"
              args: [ x ]
  - platform: homeassistant
    id: buero_thermostat
    entity_id: climate.buro_2
    attribute: temperature
    internal: true
    on_value:
      then:
        - lvgl.spinbox.update:
            id: climate_buero_spinbox_id
            value: !lambda return x;