border_width: 0
shadow_width: 0
outline_width: 0
width: ${ui_climate_width}
height: ${ui_climate_height}
scrollbar_mode: "OFF"
pad_all: 0
layout:
  type: GRID
  grid_columns:
    - ${ui_climate_col_left}
    - ${ui_climate_col_center}
    - ${ui_climate_col_right}
  grid_rows:
    - ${ui_climate_row_1}
    - ${ui_climate_row_2}
    - ${ui_climate_row_3}
    - ${ui_climate_row_4}
    - ${ui_climate_row_5}
    - ${ui_climate_row_6}
  multiple_widgets_per_cell: true
  pad_column: 0
  pad_row: 0
widgets:
  # Arc Outer Ring only for visual effect
  - arc:
      id: ${id}_arc_ring_outer
      height: ${ui_climate_ring_diameter}
      width: ${ui_climate_ring_diameter}
      grid_cell_column_span: 3
      grid_cell_row_span: 5 
      grid_cell_column_pos: 0
      grid_cell_row_pos: 1
      grid_cell_x_align: CENTER
      grid_cell_y_align: CENTER
      align: CENTER
      arc_color: ${color_light_grey}
      arc_opa: COVER
      arc_width: ${ui_climate_ring_width}
      arc_rounded: false
      start_angle: 140
      end_angle: 40
      knob:
        bg_color: ${color_white}
  # # Arc Inner Ring only for visual effect
  - obj:
      id: ${id}_arc_ring_inner
      height: ${ui_climate_ring_diameter}
      width: ${ui_climate_ring_diameter}
      radius: ${ui_climate_ring_radius}
      grid_cell_column_span: 3
      grid_cell_row_span: 5 
      grid_cell_column_pos: 0
      grid_cell_row_pos: 1
      grid_cell_x_align: CENTER
      grid_cell_y_align: CENTER
      align: CENTER
      border_width: 40
      border_color: ${color_dark_grey}
      bg_color: ${color_darker_grey}
      # start_angle: 135
      # end_angle: 45
  # Meter ticks and needle
  - meter:
      id: ${id}_meter_ticks
      hidden: true
      height: ${ui_climate_ring_diameter}
      width: ${ui_climate_ring_diameter}
      grid_cell_column_span: 3
      grid_cell_row_span: 5 
      grid_cell_column_pos: 0
      grid_cell_row_pos: 1
      grid_cell_x_align: CENTER
      grid_cell_y_align: CENTER
      align: CENTER
      bg_opa: TRANSP
      border_width: 2
      shadow_width: 0
      scales:
        - range_from: 160   # 16°C
          range_to: 340     # 34°C
          # Set temperature ticks background
          ticks:
            count: 60
            length: 15
            width: 2
            color: ${color_temp_ticks}
          indicators:
            # Current temperature needle
            - line:
                id: ${id}_current_temp_needle
                color: ${color_temp_current}
                width: 3
                r_mod: 10
                value: 340 # 34°C Should be the same as the current temperature label
            # Set temperature ticks
            - tick_style:
                id: ${id}_hvac_temp_ticks
                start_value: 160
                end_value: 240 # 24°C Should be the same as the set temperature label
                color_start: ${color_temp_set}
                color_end: ${color_temp_set}
                width: 2
    # Meter inner Ring only for visual effect
  - obj:
      id: ${id}_meter_ring_inner
      height: ${ui_climate_meter_diameter}
      width: ${ui_climate_meter_diameter}
      grid_cell_column_span: 3
      grid_cell_row_span: 5
      grid_cell_column_pos: 0
      grid_cell_row_pos: 1
      grid_cell_x_align: CENTER
      grid_cell_y_align: CENTER
      radius: ${ui_climate_meter_radius}
      align: CENTER
      border_width: 12
      border_color: ${color_dark_grey}
      bg_color: ${color_darker_grey}
      # start_angle: 135
      # end_angle: 45
  # background for mode buttons
  - obj:
      grid_cell_column_pos: 1
      grid_cell_row_pos: 5
      grid_cell_x_align: CENTER
      grid_cell_y_align: CENTER
      width: ${ui_climate_col_center}
      height: ${ui_climate_row_5}
      radius: ${ui_climate_mode_button_radius}
      bg_color: ${color_darker_grey}
      border_width: 0
      shadow_width: 0
      outline_width: 0
  # Set temperature knob, should change with the set temperature ticks
  - arc:
      id: ${id}_hvac_temp_knob
      grid_cell_column_span: 3
      grid_cell_row_span: 5 
      grid_cell_column_pos: 0
      grid_cell_row_pos: 1
      grid_cell_x_align: CENTER
      grid_cell_y_align: CENTER
      hidden: true
      align: CENTER
      arc_opa: TRANSP
      adjustable: true
      value: 240 # 24°C (24x10) Should be the same as the set temperature needle
      min_value: 160
      max_value: 340
      width: ${ui_climate_knob_diameter}
      height: ${ui_climate_knob_diameter}
      start_angle: 140
      end_angle: 40
      arc_width: 10
      change_rate: 30
      indicator:
        arc_opa: TRANSP
        arc_width: 16
      knob:
        bg_color: ${color_temp_set}
        border_width: 4
        border_color: ${color_white}
      on_change:
        then:
          - homeassistant.action:
              action: climate.set_temperature
              data:
                entity_id: ${entity}
                temperature: !lambda |-
                  float temp = x / 10.0;
                  return roundf(temp * 2) / 2;
  # HVAC Modes: OFF, AUTO, HEAT, COOL
  - label:
      id: ${id}_mode_label
      grid_cell_column_pos: 1
      grid_cell_row_pos: 2
      grid_cell_x_align: CENTER
      grid_cell_y_align: CENTER
      align: CENTER
      text: "KPR" # HVAC mode to be updated from Home Assistant climate entity
      text_font: roboto_reg
      text_color: ${color_grey}
  # Set Temperature label, should change with the set temperature knob
  - label:
      id: ${id}_hvac_temp_label
      grid_cell_column_pos: 1
      grid_cell_row_pos: 3
      grid_cell_x_align: CENTER
      grid_cell_y_align: CENTER
      hidden: false
      align: CENTER
      text_font: roboto_huge
      text: "---" # Set temperature to be updated from Home Assistant climate entity
  # Current Temperature label, should change with the current temperature needle
  - label:
      id: ${id}_current_temp_label
      grid_cell_column_pos: 1
      grid_cell_row_pos: 4
      grid_cell_x_align: CENTER
      grid_cell_y_align: CENTER
      hidden: false
      align: CENTER
      text: "---" # Current temperature to be updated from Home Assistant climate entity
      text_color: ${color_temp_current}
  # Temperature buttons
  # HVAC increase temperature
  - button:
      id: ${id}_temp_inc_button
      hidden: true
      grid_cell_column_pos: 2
      grid_cell_row_pos: 1
      grid_cell_x_align: CENTER
      grid_cell_y_align: CENTER
      align: CENTER
      styles: style_circle_button
      bg_color: ${color_red}
      widgets:
        - label:
            styles: style_circle_label
            text: ${mdi_plus}
            text_color: ${color_white}
      on_press:
        - script.execute:
            id: ${id}_set_hvac_temp
            direction: "up"
  # HVAC decrease temperature
  - button:
      id: ${id}_temp_dec_button
      hidden: true
      grid_cell_column_pos: 2
      grid_cell_row_pos: 5
      grid_cell_x_align: CENTER
      grid_cell_y_align: CENTER
      align: CENTER
      styles: style_circle_button
      bg_color: ${color_blue}
      widgets:
        - label:
            styles: style_circle_label
            text: ${mdi_minus}
            text_color: ${color_white}
      on_press:
        - script.execute:
            id: ${id}_set_hvac_temp
            direction: "down"
  # comfort temperature
  - button:
      id: ${id}_temp_comfort_button
      hidden: true
      grid_cell_column_pos: 0
      grid_cell_row_pos: 1
      grid_cell_x_align: CENTER
      grid_cell_y_align: CENTER
      align: CENTER
      styles: style_menu_button
      bg_color: ${color_red}
      widgets:
        - label:
            styles: style_menu_button_label
            text: ${temperature_comfort}
            text_color: ${color_white}
      on_press:
        - homeassistant.action:
            action: climate.set_temperature
            data:
              entity_id: ${entity}
              temperature: ${temperature_comfort}
  # absenk temperature
  - button:
      id: ${id}_temp_lowering_button
      hidden: true
      grid_cell_column_pos: 0
      grid_cell_row_pos: 5
      grid_cell_x_align: CENTER
      grid_cell_y_align: CENTER
      align: CENTER
      styles: style_menu_button
      bg_color: ${color_blue}
      widgets:
        - label:
            styles: style_menu_button_label
            text: ${temperature_lowering}
            text_color: ${color_white}
      on_press:
        - homeassistant.action:
            action: climate.set_temperature
            data:
              entity_id: ${entity}
              temperature: ${temperature_lowering}
  # HVAC Mode buttons
  # POWER
  - button:
      id: ${id}_power_button
      grid_cell_column_pos: 1
      grid_cell_row_pos: 5
      grid_cell_x_align: START
      grid_cell_y_align: CENTER
      align: CENTER
      bg_opa: TRANSP
      styles: style_mode_button
      widgets:
        - label:
            id: ${id}_power_button_label
            styles: style_menu_button_label
            text: ${mdi_power} 
            text_color: ${color_grey}
      on_press:
        - if:
            condition:
              lambda: 'return id(${id}_hvac_mode).state == "off";'
            then:
              - homeassistant.action:
                  action: climate.set_hvac_mode
                  data:
                    entity_id: ${entity}
                    hvac_mode: "cool"
            else:
              - homeassistant.action:
                  action: climate.set_hvac_mode
                  data:
                    entity_id: ${entity}
                    hvac_mode: "off"
  # HEAT
  - button:
      id: ${id}_heat_button
      grid_cell_column_pos: 1
      grid_cell_row_pos: 5
      grid_cell_x_align: END
      grid_cell_y_align: CENTER
      align: CENTER
      bg_opa: TRANSP
      styles: style_mode_button
      widgets:
        - label:
            id: ${id}_heat_button_label
            styles: style_menu_button_label
            text: ${mdi_mode_heat}
            text_color: ${color_grey}
      on_press:
        - homeassistant.action:
            action: climate.set_hvac_mode
            data:
              entity_id: ${entity}
              hvac_mode: "heat"
  - label:
      grid_cell_column_pos: 0
      grid_cell_row_pos: 0
      grid_cell_column_span: 3
      grid_cell_x_align: CENTER
      grid_cell_y_align: CENTER
      align: CENTER
      text: ${title}
      text_align: CENTER
      text_color: ${color_black}
      bg_color: ${color_grey}
