style_definitions:
  - id: header_footer
    bg_color: ${color_dark_grey}
    bg_grad_color: ${color_dark_grey}
    bg_grad_dir: VER
    bg_opa: COVER
    border_opa: TRANSP
    radius: 0
    pad_all: 0
    pad_row: 0
    pad_column: 0
    border_color: 0x0080b5
    text_color: 0xFFFFFF
    width: 100%
    height: ${ui_footer_height}
  - id: entity_widget
    bg_color: 0xFFFFFFF
    bg_grad_color: 0xFFFFFF
    bg_grad_dir: VER
    bg_opa: COVER
    border_opa: TRANSP
    radius: 0
    pad_all: 0
    pad_row: 0
    pad_column: 0
    border_color: 0x0080b5
    text_color: 0x000000
    width: 50%
    height: ${ui_header_height}
  - id: style_menu_button
    bg_opa: COVER
    bg_color: ${color_darker_grey}
    shadow_opa: 50%
    shadow_color: ${color_darker_grey}
    outline_width: 1
    outline_color: ${color_dark_grey}
  - id: style_menu_button_label
    align: CENTER
    text_font: roboto_med
  - id: style_circle_button_mini
    bg_color: ${color_dark_grey}
    shadow_opa: 50%
    shadow_color: ${color_grey}
    outline_width: 1
    outline_color: ${color_darker_grey}
    pad_all: 1
    align: CENTER
    text_font: roboto_reg  
    text_color: ${color_white}
    text_align: CENTER
    radius: 10
  - id: style_circle_button
    bg_color: ${color_darker_grey}
    shadow_opa: 50%
    shadow_color: ${color_darker_grey}
    outline_width: 1
    outline_color: ${color_dark_grey}
    radius: 15
  - id: style_mode_button
    bg_opa: COVER 
    radius: 50
    outline_width: 1
  - id: style_circle_label
    align: center
    text_align: center
    text_font: roboto_med
