substitutions:
  node_name: "7B-sample"

packages:
  - !include common/subst.yaml
  - !include common/wifi.yaml
  - !include boards/ESP32-S3-Touch-LCD-7.yaml
  # - !include packages/pglivingroom_sensors.yaml
  - !include
      file: packages/pgclimate_sensor.yaml
      vars:
        title: "Office"
        id: buro
        entity: climate.buro
  - !include
      file: packages/pgclimate_sensor.yaml
      vars:
        title: "Living Room"
        id: wohn
        entity: climate.wohnzimmer
  - !include
      file: packages/pgclimate_sensor.yaml
      vars:
        title: "Left"
        id: wohnl
        entity: climate.wohn_l
  - !include
      file: packages/pgclimate_sensor.yaml
      vars:
        title: "Center"
        id: wohnc
        entity: climate.wohn_c
  - !include
      file: packages/pgclimate_sensor.yaml
      vars:
        title: "Basement"
        id: keller
        entity: climate.keller
  - !include
      file: packages/pgclimate_sensor.yaml
      vars:
        title: "Bedroom"
        id: schlafzimmer
        entity: climate.schlafzimmer




lvgl:
  pages:
#    - <<: !include common/pglivingroom.yaml
    - id: main_page
      widgets:
        - obj:
            id: climate_header
            align: TOP_MID
            styles: header_footer
            widgets:
              - label:
                  text: "Heating Control"
                  align: CENTER
                  text_align: CENTER
                  text_color: 0xFFFFFF
        - obj:
            id: climate_body
            align: top_left
            y: 30
            width: 800
            height: 420
            border_width: 0
            shadow_width: 0
            outline_width: 0
            pad_all: 0
            layout:
              type: grid
              grid_rows: [ 210px, 210px ]
              grid_columns: [ content, content, content ]
              pad_row: 0
              pad_column: 0
            widgets:
              - obj:
                  grid_cell_row_pos : 1
                  grid_cell_column_pos : 0
                  <<: !include 
                    file: gui/climate.yaml
                    vars: 
                      id: buro
                      entity: climate.buro
                      title: "Office"
              - obj:
                  grid_cell_row_pos : 1
                  grid_cell_column_pos : 1
                  <<: !include 
                    file: gui/climate.yaml
                    vars: 
                      id: keller
                      entity: climate.keller
                      title: "Basement"
              - obj:
                  grid_cell_row_pos : 1
                  grid_cell_column_pos : 2
                  <<: !include 
                    file: gui/climate.yaml
                    vars: 
                      id: schlafzimmer
                      entity: climate.schlafzimmer
                      title: "Bedroom"
              - obj:
                  grid_cell_row_pos : 0
                  grid_cell_column_pos : 0
                  <<: !include 
                    file: gui/climate.yaml
                    vars: 
                      id: wohn
                      entity: climate.wohnzimmer
                      title: "Living Room"
              - obj:
                  grid_cell_row_pos : 0
                  grid_cell_column_pos : 1
                  <<: !include 
                    file: gui/climate.yaml
                    vars: 
                      id: wohnl
                      entity: climate.wohn_l
                      title: "Left"
              - obj:
                  grid_cell_row_pos : 0
                  grid_cell_column_pos : 2
                  <<: !include 
                    file: gui/climate.yaml
                    vars: 
                      id: wohnc
                      entity: climate.wohn_c
                      title: "Center"

