substitutions:
  node_name: "esp32p4-10-sample"
  friendly_name: p47b
  ha_token: !secret ha_long_lived_token

packages:
  - !include common/subst.yaml
  - !include common/wifi.yaml
  - !include
      file: boards/ESP32-P4-WIFI6-TOUCH-LCD-10.1.yaml
      vars:
        rotation: 270
  # - !include packages/pglivingroom_sensors.yaml
  - !include
      file: packages/pgclimate_sensor.yaml
      vars:
        title: "Office"
        id: buro
        entity: climate.buro
  - !include
      file: packages/pgclimate_sensor.yaml
      vars:
        title: "Living Room"
        id: wohn
        entity: climate.wohnzimmer
  - !include
      file: packages/pgclimate_sensor.yaml
      vars:
        title: "Left"
        id: wohnl
        entity: climate.wohn_l
  - !include
      file: packages/pgclimate_sensor.yaml
      vars:
        title: "Center"
        id: wohnc
        entity: climate.wohn_c
  - !include
      file: packages/pgclimate_sensor.yaml
      vars:
        title: "Basement"
        id: keller
        entity: climate.keller
  - !include
      file: packages/pgclimate_sensor.yaml
      vars:
        title: "Bedroom"
        id: schlafzimmer
        entity: climate.schlafzimmer
  - !include common/pgweather.yaml
  # DISABLED: voice.yaml for memory optimization
  # - !include common/voice.yaml
  - !include common/history_charts.yaml

select:
  - platform: template
    name: LVGL Page
    id: lvgl_page_select
    optimistic: true
    options:
      - Climate
      - Weather Daily
      - Weather Hourly
      - History
    initial_option: Climate
    set_action:
      - if:
          condition:
            lambda: return x == "Climate";
          then:
            - lvgl.page.show: main_page
      - if:
          condition:
            lambda: return x == "Weather Daily";
          then:
            - lvgl.page.show: weather_page_daily
      - if:
          condition:
            lambda: return x == "Weather Hourly";
          then:
            - lvgl.page.show: weather_page_hourly
      - if:
          condition:
            lambda: return x == "History";
          then:
            - lvgl.page.show: history_page

lvgl:
  on_boot:
    - lvgl.page.show: main_page
  pages:
#    - <<: !include common/pglivingroom.yaml
    - id: main_page
      on_load:
        - lambda: |-
            id(lvgl_page_select).publish_state("Climate");
      widgets:
        - obj:
            id: climate_header
            align: TOP_MID
            styles: header_footer
            widgets:
              - label:
                  text: "Heating Control"
                  align: CENTER
                  text_align: CENTER
                  text_color: 0xFFFFFF
        - obj:
            id: climate_body
            align: top_left
            y: ${ui_header_height}
            width: 100%
            height: ${ui_page_height}
            scrollbar_mode: "OFF"
            scrollable: false
            # height: !lambda |- 
            #   int h = lv_obj_get_height(lv_scr_act()); 
            #   return h -60; // adjust for header/footer
            border_width: 0
            shadow_width: 0
            outline_width: 0
            pad_all: 0
            layout:
              type: grid
              grid_rows: [ fr(1), fr(1) ]
              grid_columns: [ fr(1), fr(1), fr(1) ]
              pad_row: 0
              pad_column: 0
            widgets:
              - obj:
                  grid_cell_row_pos : 1
                  grid_cell_column_pos : 0
                  <<: !include 
                    file: gui/climate.yaml
                    vars: 
                      id: buro
                      entity: climate.buro
                      title: "Office"
              - obj:
                  grid_cell_row_pos : 1
                  grid_cell_column_pos : 1
                  <<: !include 
                    file: gui/climate.yaml
                    vars: 
                      id: keller
                      entity: climate.keller
                      title: "Basement"
              - obj:
                  grid_cell_row_pos : 1
                  grid_cell_column_pos : 2
                  <<: !include 
                    file: gui/climate.yaml
                    vars: 
                      id: schlafzimmer
                      entity: climate.schlafzimmer
                      title: "Bedroom"
              - obj:
                  grid_cell_row_pos : 0
                  grid_cell_column_pos : 0
                  <<: !include 
                    file: gui/climate.yaml
                    vars: 
                      id: wohn
                      entity: climate.wohnzimmer
                      title: "Living Room"
              - obj:
                  grid_cell_row_pos : 0
                  grid_cell_column_pos : 1
                  <<: !include 
                    file: gui/climate.yaml
                    vars: 
                      id: wohnl
                      entity: climate.wohn_l
                      title: "Left"
              - obj:
                  grid_cell_row_pos : 0
                  grid_cell_column_pos : 2
                  <<: !include 
                    file: gui/climate.yaml
                    vars: 
                      id: wohnc
                      entity: climate.wohn_c
                      title: "Center"
    - <<: !include gui/history_page.yaml

