height: SIZE_CONTENT
width: SIZE_CONTENT
bg_color: gray50
radius: 0
border_width: 0
shadow_width: 0
outline_width: 0
pad_top: 0
layout:
  type: flex
  flex_flow: COLUMN
  flex_align_cross: center
  flex_align_track: center
  pad_column: 0
  pad_row: 0
grid_cell_row_pos: ${row}
grid_cell_column_pos: ${col}
widgets:
    - label:
        id: forecast_day_${id}
        height: SIZE_CONTENT
        text: ??? 
        align: CENTER
    - label:
        id: forecast_condition_icon_${id}
        height: SIZE_CONTENT
        text_font: weather_symbols_80
        text: ${mdi_unknown}
    - label:
        id: forecast_description_${id}
        height: 32
        text_font: font_small
        text_color: dodgerblue
        text: ""
        align: CENTER
        width: 100
    - label:
        id: forecast_temperature_hi_${id}
        height: SIZE_CONTENT
        text: "---°"
    - label:
        id: forecast_temperature_lo_${id}
        height: SIZE_CONTENT
        text_font: font_small
        text_color: dodgerblue
        text: "---°"
    - label:
        id: forecast_snow_${id}
        height: SIZE_CONTENT
        text_font: font_small
        text_color: gray
        text: "${mdi_snowy} "
    - label:
        id: forecast_rain_${id}
        height: SIZE_CONTENT
        text_font: font_small
        text_color: gray
        text: "${mdi_rainy} "
    - label:
        id: forecast_wind_${id}
        height: SIZE_CONTENT
        text_font: font_small
        text_color: gray
        text: "${mdi_windy} "
    - label:
        id: forecast_sunrise_${id}
        height: SIZE_CONTENT
        text_font: font_small
        text_color: ep_orange
        text: "${mdi_sunny} --:--"
        align: CENTER
    - label:
        id: forecast_sunset_${id}
        height: SIZE_CONTENT
        text_font: font_small
        text_color: white
        bg_color: black
        bg_opa: 100%
        text: "${mdi_clear_night} --:--"
        align: CENTER

