height: SIZE_CONTENT
width: SIZE_CONTENT
bg_color: gray50
pad_top: 0
pad_bottom : 0
border_width: 0
shadow_width: 0
outline_width: 0
layout:
  type: flex
  flex_flow: COLUMN
  flex_align_cross: START
  flex_align_track: START
  pad_column: 0
  pad_row: 0
grid_cell_row_pos: ${row}
grid_cell_column_pos: ${col}
widgets:
  - label:
      height: SIZE_CONTENT
      text_font: font_small
      text_color: gray
      text: " "
      align: LEFT_MID
  - label:
      height: SIZE_CONTENT
      text_font: font_small
      text_color: gray
      hidden: true
      text: ""
  - label:
      height: SIZE_CONTENT
      text_font: font_small
      text_color: gray
      text: "°C"
  - label:
      height: SIZE_CONTENT
      text_font: font_small
      text_color: gray
      text: "%"
      hidden: true
  - label:
      height: SIZE_CONTENT
      text_font: font_small
      text_color: gray
      text: "${mdi_rainy}mm"
  - label:
      height: SIZE_CONTENT
      text_font: font_small
      text_color: gray
      text: "${mdi_snowy}mm"
  - label:
      height: SIZE_CONTENT
      text_font: font_small
      text_color: gray
      text: "${mdi_windy}㎧"
