font:
  - file: 'fonts/RobotoMono-SemiBold.ttf'    # Monospace font file
    id: font_mono
    size: ${ui_header_font_size}
  - file: 'fonts/RobotoCondensed-Regular.ttf'    # font file
    id: font_large
    bpp: 4
    size: ${ui_title_font_size}
    glyphsets:
    - GF_Latin_Core
    extras:
      - file: "fonts/MaterialSymbolsSharp-SemiBold.ttf"
        glyphs: 
          - ${mdi_humidity_percentage} 
          - ${mdi_thermometer}
    ignore_missing_glyphs: true
  - file: 'fonts/RobotoCondensed-Regular.ttf'    # font file
    id: font_norm
    bpp: 4
    size: ${ui_norm_font_size}
    glyphsets:
    - GF_Latin_Core
    extras:
      - file: "fonts/MaterialSymbolsSharp-SemiBold.ttf"
        glyphs: 
          - ${mdi_humidity_percentage} 
          - ${mdi_thermometer}
    ignore_missing_glyphs: true
  - file: 'fonts/RobotoCondensed-Regular.ttf'    # font file
    id: font_small
    bpp: 4
    size: ${ui_small_font_size}
    glyphsets:
    - GF_Latin_Core
    ignore_missing_glyphs: true
    extras:
      - file: "fonts/MaterialSymbolsSharp-SemiBold.ttf"
        glyphs: 
          - ${mdi_clear_night}
          - ${mdi_cloudy}
          - ${mdi_exceptional}
          - ${mdi_fog}
          - ${mdi_rainy}
          - ${mdi_snowy}
          - ${mdi_thunderstorm}
          - ${mdi_windy}
          - ${mdi_hail}
          - ${mdi_lightning}
          - ${mdi_lightning_rainy}
          - ${mdi_partlycloudy}
          - ${mdi_rainy_night}
          - ${mdi_snowy_night}
          - ${mdi_pouring}
          - ${mdi_sunny}
          - ${mdi_sunny_off}
          - ${mdi_unknown}
          - ${mdi_unavailable}
          - ${mdi_wb_twilight}

  - file: "fonts/MaterialSymbolsSharp-SemiBold.ttf"
    id: battery_icons_20
    size: ${ui_header_font_size}
    bpp: 4
    glyphs: 
      - ${mdi_battery_10}
      - ${mdi_battery_20}
      - ${mdi_battery_30}
      - ${mdi_battery_40}
      - ${mdi_battery_50}
      - ${mdi_battery_60}
      - ${mdi_battery_70}
      - ${mdi_battery_80}
      - ${mdi_battery_90}
      - ${mdi_battery}
      - ${mdi_battery_outline}
      - ${mdi_battery_unknown}
  - file: "fonts/MaterialSymbolsSharp-SemiBold.ttf"
    id: weather_symbols_80
    size: ${ui_weather_symbol_size}
    bpp: 4
    glyphs:
      - ${mdi_clear_night}
      - ${mdi_cloudy}
      - ${mdi_exceptional}
      - ${mdi_fog}
      - ${mdi_rainy}
      - ${mdi_snowy}
      - ${mdi_thunderstorm}
      - ${mdi_windy}
      - ${mdi_hail}
      - ${mdi_lightning}
      - ${mdi_lightning_rainy}
      - ${mdi_partlycloudy}
      - ${mdi_rainy_night}
      - ${mdi_snowy_night}
      - ${mdi_pouring}
      - ${mdi_sunny}
      - ${mdi_sunny_off}
      - ${mdi_unknown}
      - ${mdi_unavailable}
      - ${mdi_wb_twilight}
    ignore_missing_glyphs: true
  - file: "fonts/MaterialSymbolsSharp-SemiBold.ttf"
    id: weather_symbols_64
    size: ${ui_weather_symbol_smallersize}
    bpp: 4
    glyphs:
      - ${mdi_clear_night}
      - ${mdi_cloudy}
      - ${mdi_exceptional}
      - ${mdi_fog}
      - ${mdi_rainy}
      - ${mdi_snowy}
      - ${mdi_thunderstorm}
      - ${mdi_windy}
      - ${mdi_hail}
      - ${mdi_lightning}
      - ${mdi_lightning_rainy}
      - ${mdi_partlycloudy}
      - ${mdi_rainy_night}
      - ${mdi_snowy_night}
      - ${mdi_pouring}
      - ${mdi_sunny}
      - ${mdi_sunny_off}
      - ${mdi_unknown}
      - ${mdi_unavailable}
      - ${mdi_wb_twilight}
    ignore_missing_glyphs: true
  - file: "fonts/MaterialSymbolsSharp-SemiBold.ttf"
    id: weather_symbols_40
    size: ${ui_weather_symbol_smallsize}
    bpp: 4
    glyphs:
      - ${mdi_clear_night}
      - ${mdi_cloudy}
      - ${mdi_exceptional}
      - ${mdi_fog}
      - ${mdi_rainy}
      - ${mdi_snowy}
      - ${mdi_thunderstorm}
      - ${mdi_windy}
      - ${mdi_hail}
      - ${mdi_lightning}
      - ${mdi_lightning_rainy}
      - ${mdi_partlycloudy}
      - ${mdi_rainy_night}
      - ${mdi_snowy_night}
      - ${mdi_pouring}
      - ${mdi_sunny}
      - ${mdi_sunny_off}
      - ${mdi_unknown}
      - ${mdi_unavailable}
      - ${mdi_wb_twilight}
    ignore_missing_glyphs: true
  - file: 'fonts/RobotoCondensed-Regular.ttf'
    glyphs: ' 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ°.:/+-%–'
    id: roboto_reg
    size: ${ui_header_font_size}
    bpp: 4
    ignore_missing_glyphs: true
    extras:
      - file: "fonts/MaterialSymbolsSharp-SemiBold.ttf"
        glyphs: 
          - ${mdi_wifi}
          - ${mdi_wifi_off}
          - ${mdi_info}
          - ${mdi_power}
          - ${mdi_sleep}
          - ${mdi_restart}
          - ${mdi_mode_heat}

  - file: 'fonts/RobotoCondensed-Regular.ttf'
    id: roboto_med
    glyphs: ' 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ°.:/+-%–'
    size: ${ui_title_font_size}
    bpp: 4
    extras:
      - file: "fonts/MaterialSymbolsSharp-SemiBold.ttf"
        glyphs:
          - ${mdi_info}
          - ${mdi_power}
          - ${mdi_plus}
          - ${mdi_minus}
          - ${mdi_mode_heat}
    ignore_missing_glyphs: true

  - file: 'fonts/RobotoCondensed-Regular.ttf'
    glyphs: ' -0123456789.°C'
    id: roboto_huge
    size: ${ui_huge_font_size}
    bpp: 4 
