id: ${id}_climate_page_id
widgets:
  - obj:
      id: ${id}_climate_header
      align: TOP_MID
      styles: header_footer
      widgets:
        - label:
            text: ${title}
            align: CENTER
            text_align: CENTER
            text_color: 0xFFFFFF
  - obj:
      id: ${id}_climate_body
      align: top_left
      y: 30
      width: 100%
      height: 430
      <<: !include 
          file: ../gui/climate.yaml
          vars: 
            id: ${id}
            entity: ${entity}
            title: ${title}
