id: pglivingroom
widgets:
- obj:
    align: TOP_MID
    styles: header_footer
    widgets:
      - label:
          text: "Wohnzimmer"
          align: CENTER
          text_align: CENTER
          text_color: 0xFFFFFF
- obj:  
    align: top_left
    y: 30
    width: 800
    height: 430
    layout:
      type: grid
      grid_row_align: start
      grid_column_align: start
      grid_rows: [CONTENT,CONTENT,CONTENT,CONTENT,CONTENT,CONTENT,CONTENT,CONTENT,CONTENT]
      grid_columns: [CONTENT,CONTENT]
      pad_row: 4
      pad_column: 4
    widgets:
      - obj:
          grid_cell_row_pos: 0
          grid_cell_column_pos: 0
          <<: !include { file: ../gui/switch.yaml, vars: { id: pglivingroom_wohn, entity: switch.st_wohn, text: "Wohnzimmer" } } 
      - obj:
          grid_cell_row_pos: 1
          grid_cell_column_pos: 0
          <<: !include { file: ../gui/switch.yaml, vars: { id: pglivingroom_in4, entity: switch.antela_in4_socket_1, text: "Schrank links" } } 
      - obj:
          grid_cell_row_pos: 2
          grid_cell_column_pos: 0
          <<: !include { file: ../gui/switch.yaml, vars: { id: pglivingroom_in2, entity: switch.antela_in2_socket_1, text: "Schrank rechts" } } 
      - obj:
          grid_cell_row_pos: 3
          grid_cell_column_pos: 0
          <<: !include { file: ../gui/switch.yaml, vars: { id: pglivingroom_autolicht, entity: automation.wohnzimmer, text: "Autolicht" } } 
      - obj:
          grid_cell_row_pos: 4
          grid_cell_column_pos: 0
          <<: !include { file: ../gui/switch.yaml, vars: { id: pglivingroom_tv, entity: media_player.tv_wohnzimmer, text: "TV" } } 
      - obj:
          grid_cell_row_pos: 5
          grid_cell_column_pos: 0
          <<: !include { file: ../gui/switch.yaml, vars: { id: pglivingroom_socket_1, entity: switch.steckdosenleiste_socket_1, text: "Tannenbaum" } } 
      - obj:
          grid_cell_row_pos: 6
          grid_cell_column_pos: 0
          <<: !include { file: ../gui/switch.yaml, vars: { id: pglivingroom_socket_2, entity: switch.steckdosenleiste_socket_2, text: "SL 2" } } 
      - obj:
          grid_cell_row_pos: 7
          grid_cell_column_pos: 0
          <<: !include { file: ../gui/switch.yaml, vars: { id: pglivingroom_socket_3, entity: switch.steckdosenleiste_socket_3, text: "Lichterkette" } } 
    #   - obj:
    #       grid_cell_row_pos: 0
    #       grid_cell_column_pos: 1
    #       <<: !include { file: ../gui/temperature.yaml, vars: { id: pglivingroom_dect210, entity: dect_210_temperature_2, text: "Steckdose Terasse" } } 
    #   - obj:
    #       grid_cell_row_pos: 2
    #       grid_cell_column_pos: 1
    #       <<: !include { file: ../gui/temperature.yaml, vars: { id: pglivingroom_pool_lower, entity: pool_lower, text: "Pool unten" } } 
    #   - obj:
    #       grid_cell_row_pos: 1
    #       grid_cell_column_pos: 1
    #       <<: !include { file: ../gui/temperature.yaml, vars: { id: pglivingroom_pool_upper, entity: pool_upper, text: "Pool oben" } } 
      - obj:
          grid_cell_row_pos: 0
          grid_cell_column_pos: 1
          <<: !include { file: ../gui/temperature.yaml, vars: { id: pglivingroom_outside_temperature,  entity: outside_temperature_2, text: "Terasse Temperatur" } } 
      - obj:
          grid_cell_row_pos: 1
          grid_cell_column_pos: 1
          <<: !include { file: ../gui/humidity.yaml, vars: { id: pglivingroom_outside_humidity,  entity: outside_humidity_2, text: "Luftfeuchte" } } 
      - obj:
          grid_cell_row_pos: 2
          grid_cell_column_pos: 1
          <<: !include { file: ../gui/pressure.yaml, vars: { id: pglivingroom_outside_pressure,  entity: outside_pressure_2, text: "Luftdruck" } } 
      - obj:
          grid_cell_row_pos: 3
          grid_cell_column_pos: 1
          <<: !include { file: ../gui/temperature.yaml, vars: { id: 7i_wohn_bme280_temperature,  entity: 7i_wohn_bme280_temperature, text: "Innen Temperatur" } } 
      - obj:
          grid_cell_row_pos: 4
          grid_cell_column_pos: 1
          <<: !include { file: ../gui/humidity.yaml, vars: { id: 7i_wohn_bme280_humidity,  entity: 7i_wohn_bme280_humidity, text: "Luftfeuchte" } } 
      - obj:
          grid_cell_row_pos: 5
          grid_cell_column_pos: 1
          <<: !include { file: ../gui/pressure.yaml, vars: { id: 7i_wohn_bme280_pressure,  entity: 7i_wohn_bme280_pressure, text: "Luftdruck" } } 
      - obj:
          grid_cell_row_pos: 6
          grid_cell_column_pos: 1
          <<: !include { file: ../gui/switch.yaml, vars: { id: pglivingroom_carport, entity: input_boolean.carport, text: "Carport" } } 
      - obj:
          grid_cell_row_pos: 7
          grid_cell_column_pos: 1
          align: BOTTOM_MID
          y: -50
          width: SIZE_CONTENT
          height: SIZE_CONTENT
          layout:
            type: FLEX
            flex_flow: ROW
            flex_align_cross: CENTER
          widgets:
            - button:
                id: pglivingroom_thermostat_spin_down
                width: 50
                height: 50
                on_click:
                  - lvgl.spinbox.decrement: pglivingroom_thermostat_spinbox
                widgets:
                  - label:
                      text: "-"
            - spinbox:
                id: pglivingroom_thermostat_spinbox
                align: CENTER
                text_align: CENTER
                width: 100
                height: 50
                range_from: 15
                range_to: 35
                selected_digit: 0
                rollover: false
                digits: 3
                decimal_places: 1
                on_value:
                  then:
                    - homeassistant.action:
                        action: climate.set_temperature
                        data:
                          temperature: !lambda return x;
                          entity_id: climate.wohnzimmer
            - button:
                id: pglivingroom_thermostat_spin_up
                width: 50
                height: 50
                on_click:
                  - lvgl.spinbox.increment: pglivingroom_thermostat_spinbox
                widgets:
                  - label:
                      text: "+"