id: main_page
widgets:
- obj:
    align: TOP_MID
    styles: header_footer
    widgets:
      - label:
          text: "Home"
          align: CENTER
          text_align: CENTER
          text_color: 0xFFFFFF
- obj:
    align: top_left
    y: 30
    width: 800
    height: 430
    layout:
      type: grid
      grid_row_align: start
      grid_column_align: start
      grid_rows: [CONTENT,CONTENT,CONTENT,CONTENT,CONTENT,CONTENT,CONTENT,CONTENT]
      grid_columns: [FR(1),FR(1), FR(1), FR(1)]
      pad_row: 4
      pad_column: 4
    widgets:
      - obj:
          grid_cell_row_pos: 0
          grid_cell_column_pos: 0
          grid_cell_column_span: 2
          <<: !include { file: ../gui/switch.yaml, vars: { id: buro, entity: switch.st_buro, text: "Büro" } } 
      - obj:
          grid_cell_row_pos: 1
          grid_cell_column_pos: 0
          grid_cell_column_span: 2
          <<: !include { file: ../gui/switch.yaml, vars: { id: buerom, entity: switch.st_buerom, text: "Monitore" } } 
      - obj:
          grid_cell_row_pos: 2
          grid_cell_column_pos: 0
          grid_cell_column_span: 2
          <<: !include { file: ../gui/switch.yaml, vars: { id: keller,  entity: switch.st_keller, text: "Keller" } } 
      - obj:
          grid_cell_row_pos: 3
          grid_cell_column_pos: 0
          grid_cell_column_span: 2
          <<: !include { file: ../gui/temperature.yaml, vars: { id: 7inch_bme280_temperature,  entity: 7inch_bme280_temperature, text: "Temperatur" } } 
      - obj:
          grid_cell_row_pos: 4
          grid_cell_column_pos: 0
          grid_cell_column_span: 2
          <<: !include { file: ../gui/humidity.yaml, vars: { id: 7inch_bme280_humidity,  entity: 7inch_bme280_humidity, text: "Luftfeuchte" } } 
      - obj:
          grid_cell_row_pos: 5
          grid_cell_column_pos: 0
          grid_cell_column_span: 2
          <<: !include { file: ../gui/pressure.yaml, vars: { id: 7inch_bme280_pressure,  entity: 7inch_bme280_pressure, text: "Luftdruck" } } 
      - label:
          grid_cell_row_pos: 6
          grid_cell_column_pos: 1
          text: "Battery"
          align: LEFT_MID
      - label:
          grid_cell_row_pos: 6
          grid_cell_column_pos: 0
          id: voltage_text
          text: "-.--V"
          align: RIGHT_MID
      - obj:
          grid_cell_row_pos: 0
          grid_cell_column_pos: 2
          grid_cell_column_span: 2
          grid_cell_row_span: 2
          align: BOTTOM_MID
          y: -50
          width: SIZE_CONTENT
          height: SIZE_CONTENT
          layout:
            type: FLEX
            flex_flow: ROW
            flex_align_cross: CENTER
          widgets:
            - button:
                id: climate_buero_spin_down
                width: 50
                height: 50
                on_click:
                  - lvgl.spinbox.decrement: climate_buero_spinbox_id
                widgets:
                  - label:
                      text: "-"
            - spinbox:
                id: climate_buero_spinbox_id
                align: CENTER
                text_align: CENTER
                width: 100
                height: 50
                range_from: 15
                range_to: 35
                selected_digit: 0
                rollover: false
                digits: 3
                decimal_places: 1
                on_value:
                  then:
                    - homeassistant.action:
                        action: climate.set_temperature
                        data:
                          temperature: !lambda return x;
                          entity_id: climate.buro_2
            - button:
                id: spin_up
                width: 50
                height: 50
                on_click:
                  - lvgl.spinbox.increment: climate_buero_spinbox_id
                widgets:
                  - label:
                      text: "+"

