substitutions:
  # Material Design Icons
  mdi_wifi: "\U0000e63e"
  mdi_wifi_off: "\U0000e648"
  mdi_power: "\U0000e8ac"
  mdi_info:  "\U0000e88e"
  mdi_mode_heat: "\U0000f16a"
  mdi_restart: "\U0000f053"
  mdi_sleep: "\U0000e046"
  mdi_thermometer: "\U0000E846"
  mdi_thermostat_auto: "\U000Ff027"
  mdi_chevron_up: "\U000F0143"
  mdi_chevron_down: "\U000F0140"
  mdi_plus:         "\U0000f582"
  mdi_minus:        "\U0000f581"
  mdi_humidity_percentage: "\U0000F87E"
  mdi_battery_10: "\U0000EBD9"
  mdi_battery_20: "\U0000EBE0"
  mdi_battery_30: "\U0000EBDD"
  mdi_battery_40: "\U0000EBE2"
  mdi_battery_50: "\U0000EBD4"
  mdi_battery_60: "\U0000EBD2"
  mdi_battery_70: "\U0000F09E"
  mdi_battery_80: "\U0000F09F"
  mdi_battery_90: "\U0000F0A0"
  mdi_battery:    "\U0000F0A1"
  mdi_battery_outline: "\U0000F13B"
  mdi_battery_unknown: "\U0000E1A6"
  # Colors common
  color_white: "0xFFFFFF"
  color_black: "0x000000"
  color_grey: "0xa5a5a5"
  color_red: "0xff0000"
  color_blue: "0x0000ff"
  color_dark_grey: "0x282828"
  color_darker_grey: "0x212121"
  color_light_grey: "0xcccccc"
  color_accent: "0x18bcf2"
  color_warning: "0xd2691e"
  color_success: "0x7fff00"
  # Mode colors
  color_auto: "0x2fd1c5"
  color_cool: "0x00bfff"
  color_heat: "0xff1493"
  color_dry: "0xff8c00"
  color_fan: "0x87ceeb"
  # Temperature colors
  color_temp_current: "0x35ffe6"
  color_temp_set: "0x51a0e4"
  color_temp_ticks: "0x585858"
  # temperatures
  temperature_lowering: "16.0"
  temperature_comfort: "22.5"
